# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-06-09 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LostPeople', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Phone_Founder',
            field=models.IntegerField(default=0),
        ),
    ]
