# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-06-10 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LostPeople', '0004_auto_20190609_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missed',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
