# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-06-10 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LostPeople', '0005_auto_20190610_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='missed',
            name='Accept',
            field=models.BooleanField(default=False),
        ),
    ]
