# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-06-19 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LostPeople', '0008_auto_20190611_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='undefined', max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Auther', models.CharField(max_length=50)),
                ('idCard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LostPeople.Missed')),
            ],
        ),
    ]
