# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-06-19 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LostPeople', '0009_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='idCard',
            field=models.IntegerField(default=-1),
        ),
    ]
