# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-06-20 09:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LostPeople', '0010_auto_20190619_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missed',
            name='age',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
