# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-06-19 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Img',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
