# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-06-20 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20190620_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.IntegerField(default=-1)),
                ('idProduct', models.IntegerField(default=-1)),
                ('Fav', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='Fav',
        ),
    ]
