# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-06-22 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20190620_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='undefined', max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('Phone_nubmer', models.IntegerField(default=0)),
            ],
        ),
    ]
